### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by alexisph** [timescale/prometheus-postgresql-adapter#3]
I could not build the adapter on a new Linux box due to compilation errors.

Also, the build instructions miss some critical steps. I had to debug `make` not finding the go libraries that `glide` downloaded because they were not in `$HOME/go/src`.

**Comment by erimatnor** [comment]
Could you provide some more information on the compilation errors you are seeing.

FWIW, Glide isn't supposed to install dependencies in `$HOME/go/src`. It puts things in the vendor directory.

**Comment by alexisph** [comment]
Hi. I've installed Go 1.9 and Glide on a clean Ubuntu container according to https://github.com/golang/go/wiki/Ubuntu and https://glide.sh/ respectively.
I've set `$GOPATH=$HOME/go`

I then cloned this repo to `$HOME` and followed https://github.com/timescale/prometheus-postgresql-adapter#building :

1. `glide install --strip-vendor --strip-vcs` output:

```
root@633482f8518d:~/prometheus-postgresql-adapter# glide install --strip-vendor --strip-vcs
[WARN]	The --strip-vcs flag is deprecated. This now works by default.
[WARN]	The name listed in the config file (github.com/timescale/prometheus-timescaledb-adapter) does not match the current location (.)
[INFO]	Downloading dependencies. Please wait...
[INFO]	--> Found desired version locally github.com/beorn7/perks 4c0e84591b9aa9e6dcfdf3e020114cd81f89d5f9!
[INFO]	--> Found desired version locally github.com/gogo/protobuf 100ba4e885062801d56799d78530b73b178a78f3!
[INFO]	--> Found desired version locally github.com/golang/protobuf 18c9bb3261723cd5401db4d0c9fbc5c3b6c70fe8!
[INFO]	--> Found desired version locally github.com/golang/snappy 553a641470496b2327abcac10b36396bd98e45c9!
[INFO]	--> Found desired version locally github.com/lib/pq 2704adc878c21e1329f46f6e56a1c387d788ff94!
[INFO]	--> Found desired version locally github.com/matttproud/golang_protobuf_extensions c12348ce28de40eed0136aa2b644d0ee0650e56c!
[INFO]	--> Found desired version locally github.com/prometheus/client_golang c5b7fccd204277076155f10851dad72b76a49317!
[INFO]	--> Found desired version locally github.com/prometheus/client_model 6f3806018612930941127f2a7c6c453ba2c527d2!
[INFO]	--> Found desired version locally github.com/prometheus/common 13ba4ddd0caa9c28ca7b7bffe1dfa9ed8d5ef207!
[INFO]	--> Found desired version locally github.com/prometheus/procfs d098ca18df8bc825079013daf7bacefbb1ee877e!
[INFO]	--> Found desired version locally github.com/prometheus/prometheus 4666df502c0e239ed4aa1d80abbbfb54f61b23c3!
[INFO]	--> Found desired version locally github.com/Sirupsen/logrus 10f801ebc38b33738c9d17d50860f484a0988ff5!
[INFO]	--> Found desired version locally github.com/syndtr/goleveldb 8c81ea47d4c41a385645e133e15510fc6a2a74b4!
[INFO]	--> Found desired version locally golang.org/x/net feeb485667d1fdabe727840fe00adc22431bc86e!
[INFO]	--> Found desired version locally golang.org/x/sys 9ccfe848b9db8435a24c424abbc07a921adf1df5!
[INFO]	--> Found desired version locally golang.org/x/time 8be79e1e0910c292df4e79c241bb7e8f7e725959!
[INFO]	--> Found desired version locally gopkg.in/yaml.v2 cd8b52f8269e0feb286dfeef29f8fe4d5b397e0b!
[INFO]	Setting references.
[INFO]	--> Setting version for github.com/prometheus/client_golang to c5b7fccd204277076155f10851dad72b76a49317.
[INFO]	--> Setting version for github.com/prometheus/prometheus to 4666df502c0e239ed4aa1d80abbbfb54f61b23c3.
[INFO]	--> Setting version for github.com/beorn7/perks to 4c0e84591b9aa9e6dcfdf3e020114cd81f89d5f9.
[INFO]	--> Setting version for github.com/golang/protobuf to 18c9bb3261723cd5401db4d0c9fbc5c3b6c70fe8.
[INFO]	--> Setting version for github.com/prometheus/client_model to 6f3806018612930941127f2a7c6c453ba2c527d2.
[INFO]	--> Setting version for github.com/prometheus/common to 13ba4ddd0caa9c28ca7b7bffe1dfa9ed8d5ef207.
[INFO]	--> Setting version for github.com/Sirupsen/logrus to 10f801ebc38b33738c9d17d50860f484a0988ff5.
[INFO]	--> Setting version for github.com/syndtr/goleveldb to 8c81ea47d4c41a385645e133e15510fc6a2a74b4.
[INFO]	--> Setting version for github.com/prometheus/procfs to d098ca18df8bc825079013daf7bacefbb1ee877e.
[INFO]	--> Setting version for github.com/matttproud/golang_protobuf_extensions to c12348ce28de40eed0136aa2b644d0ee0650e56c.
[INFO]	--> Setting version for github.com/golang/snappy to 553a641470496b2327abcac10b36396bd98e45c9.
[INFO]	--> Setting version for github.com/lib/pq to 2704adc878c21e1329f46f6e56a1c387d788ff94.
[INFO]	--> Setting version for github.com/gogo/protobuf to 100ba4e885062801d56799d78530b73b178a78f3.
[INFO]	--> Setting version for gopkg.in/yaml.v2 to cd8b52f8269e0feb286dfeef29f8fe4d5b397e0b.
[INFO]	--> Setting version for golang.org/x/net to feeb485667d1fdabe727840fe00adc22431bc86e.
[INFO]	--> Setting version for golang.org/x/time to 8be79e1e0910c292df4e79c241bb7e8f7e725959.
[INFO]	--> Setting version for golang.org/x/sys to 9ccfe848b9db8435a24c424abbc07a921adf1df5.
[INFO]	Exporting resolved dependencies...
[INFO]	--> Exporting github.com/beorn7/perks
[INFO]	--> Exporting github.com/prometheus/client_model
[INFO]	--> Exporting github.com/prometheus/prometheus
[INFO]	--> Exporting github.com/prometheus/procfs
[INFO]	--> Exporting github.com/Sirupsen/logrus
[INFO]	--> Exporting github.com/golang/protobuf
[INFO]	--> Exporting github.com/lib/pq
[INFO]	--> Exporting github.com/golang/snappy
[INFO]	--> Exporting github.com/matttproud/golang_protobuf_extensions
[INFO]	--> Exporting github.com/prometheus/client_golang
[INFO]	--> Exporting github.com/gogo/protobuf
[INFO]	--> Exporting github.com/prometheus/common
[INFO]	--> Exporting github.com/syndtr/goleveldb
[INFO]	--> Exporting gopkg.in/yaml.v2
[INFO]	--> Exporting golang.org/x/sys
[INFO]	--> Exporting golang.org/x/time
[INFO]	--> Exporting golang.org/x/net
[INFO]	Replacing existing vendor dependencies
[INFO]	Removing nested vendor and Godeps/_workspace directories...
[INFO]	Removing: /root/prometheus-postgresql-adapter/vendor/github.com/prometheus/prometheus/vendor
[INFO]	Removing: /root/prometheus-postgresql-adapter/vendor/github.com/prometheus/prometheus/web/ui/static/vendor
```

2. `make` output:

```
root@633482f8518d:~/prometheus-postgresql-adapter# make
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -a -installsuffix cgo --ldflags '-w' -o prometheus-postgresql-adapter main.go
main.go:29:2: cannot find package "github.com/gogo/protobuf/proto" in any of:
	/usr/lib/go-1.9/src/github.com/gogo/protobuf/proto (from $GOROOT)
	/root/go/src/github.com/gogo/protobuf/proto (from $GOPATH)
main.go:30:2: cannot find package "github.com/golang/snappy" in any of:
	/usr/lib/go-1.9/src/github.com/golang/snappy (from $GOROOT)
	/root/go/src/github.com/golang/snappy (from $GOPATH)
main.go:31:2: cannot find package "github.com/prometheus/client_golang/prometheus" in any of:
	/usr/lib/go-1.9/src/github.com/prometheus/client_golang/prometheus (from $GOROOT)
	/root/go/src/github.com/prometheus/client_golang/prometheus (from $GOPATH)
main.go:32:2: cannot find package "github.com/prometheus/common/log" in any of:
	/usr/lib/go-1.9/src/github.com/prometheus/common/log (from $GOROOT)
	/root/go/src/github.com/prometheus/common/log (from $GOPATH)
main.go:33:2: cannot find package "github.com/prometheus/common/model" in any of:
	/usr/lib/go-1.9/src/github.com/prometheus/common/model (from $GOROOT)
	/root/go/src/github.com/prometheus/common/model (from $GOPATH)
main.go:36:2: cannot find package "github.com/prometheus/prometheus/storage/remote" in any of:
	/usr/lib/go-1.9/src/github.com/prometheus/prometheus/storage/remote (from $GOROOT)
	/root/go/src/github.com/prometheus/prometheus/storage/remote (from $GOPATH)
main.go:34:2: cannot find package "github.com/timescale/prometheus-postgresql-adapter/postgresql" in any of:
	/usr/lib/go-1.9/src/github.com/timescale/prometheus-postgresql-adapter/postgresql (from $GOROOT)
	/root/go/src/github.com/timescale/prometheus-postgresql-adapter/postgresql (from $GOPATH)
Makefile:30: recipe for target 'prometheus-postgresql-adapter' failed
make: *** [prometheus-postgresql-adapter] Error 1
```

```
root@633482f8518d:~/prometheus-postgresql-adapter# ls -al ~/go/src/
total 0
drwxr-xr-x 2 root root  6 Dec 10 22:01 .
drwxr-xr-x 4 root root 28 Dec 10 22:01 ..
```

**Comment by maxlock** [comment]
I created /tmp/go/src and cloned into there which gets past the error above. glide install seems to work, but make then fails. GOPATH is set to /tmp/go

```
root@prometheus30517:/tmp/go/src/prometheus-postgresql-adapter-master# make
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -a -installsuffix cgo --ldflags '-w' -o prometheus-postgresql-adapter main.go
main.go:34:2: cannot find package "github.com/timescale/prometheus-postgresql-adapter/postgresql" in any of:
	/tmp/go/src/prometheus-postgresql-adapter-master/vendor/github.com/timescale/prometheus-postgresql-adapter/postgresql (vendor tree)
	/usr/lib/go-1.7/src/github.com/timescale/prometheus-postgresql-adapter/postgresql (from $GOROOT)
	/tmp/go/src/github.com/timescale/prometheus-postgresql-adapter/postgresql (from $GOPATH)
Makefile:30: recipe for target 'prometheus-postgresql-adapter' failed
make: *** [prometheus-postgresql-adapter] Error 1
```

**Comment by maxlock** [comment]
further to my last comment, two warnings in the glide output
```
[WARN]	The --strip-vcs flag is deprecated. This now works by default.
[WARN]	The name listed in the config file (github.com/timescale/prometheus-timescaledb-adapter) does not match the current location (prometheus-postgresql-adapter-master)
```
this would explaint the timescale error

**Comment by maxlock** [comment]
...so I took out the first line of glide.yml, removing the timescale reference. seems to build now.

**Comment by alexisph** [comment]
I've set `GOPATH=/tmp/go`, cloned this repo into `/tmp/go/src`, deleted the first line of `glide.yaml` but it still will not compile:

```
root@2df305cad2e5:/tmp/go/src/prometheus-postgresql-adapter# make
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -a -installsuffix cgo --ldflags '-w' -o prometheus-postgresql-adapter main.go
main.go:34:2: cannot find package "github.com/timescale/prometheus-postgresql-adapter/postgresql" in any of:
	/tmp/go/src/prometheus-postgresql-adapter/vendor/github.com/timescale/prometheus-postgresql-adapter/postgresql (vendor tree)
	/usr/lib/go-1.9/src/github.com/timescale/prometheus-postgresql-adapter/postgresql (from $GOROOT)
	/tmp/go/src/github.com/timescale/prometheus-postgresql-adapter/postgresql (from $GOPATH)
Makefile:30: recipe for target 'prometheus-postgresql-adapter' failed
make: *** [prometheus-postgresql-adapter] Error 1
```

Glide was complaining that `[WARN]	Lock file may be out of date. Hash check of YAML failed. You may need to run 'update'`, so I ran `glide update` and then `make` again and it worked!

Anyway, now I'm running into fatal errors when running the adapter:

```
root@2df305cad2e5:/tmp/go/src/prometheus-postgresql-adapter# ./prometheus-postgresql-adapter 
./prometheus-postgresql-adapter flag redefined: log.level
panic: ./prometheus-postgresql-adapter flag redefined: log.level

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc420056060, 0xc81560, 0xc42000fa20, 0x9b228b, 0x9, 0x9cd410, 0x63)
	/usr/lib/go-1.9/src/flag/flag.go:793 +0x5e1
prometheus-postgresql-adapter/vendor/github.com/prometheus/prometheus/vendor/github.com/prometheus/common/log.AddFlags(0xc420056060)
	/tmp/go/src/prometheus-postgresql-adapter/vendor/github.com/prometheus/prometheus/vendor/github.com/prometheus/common/log/log.go:118 +0xc9
prometheus-postgresql-adapter/vendor/github.com/prometheus/prometheus/vendor/github.com/prometheus/common/log.init.0()
	/tmp/go/src/prometheus-postgresql-adapter/vendor/github.com/prometheus/prometheus/vendor/github.com/prometheus/common/log/log.go:110 +0x2d
prometheus-postgresql-adapter/vendor/github.com/prometheus/prometheus/vendor/github.com/prometheus/common/log.init()
	<autogenerated>:1 +0xc0
prometheus-postgresql-adapter/vendor/github.com/prometheus/prometheus/storage/local.init()
	<autogenerated>:1 +0x64
prometheus-postgresql-adapter/vendor/github.com/prometheus/prometheus/storage/remote.init()
	<autogenerated>:1 +0xbc
prometheus-postgresql-adapter/vendor/github.com/timescale/prometheus-postgresql-adapter/postgresql.init()
	<autogenerated>:1 +0x84
main.init()
	<autogenerated>:1 +0x9e
```

**Comment by knope** [comment]
+ ensured prometheus repo contents in `$GOPATH/src/prometheus`
+ compile steps attempted `glide install --strip-vendor `, `glide update`, `make`
+ attempted to run `prometheus-postgresql-adapter` using envars found in docker container:
```bash
PG_PROMETHEUS_ENV_PGDATA
PG_PROMETHEUS_ENV_PG_VERSION
PG_PROMETHEUS_ENV_LANG
PG_PROMETHEUS_PORT_5432_TCP_ADDR
PG_PROMETHEUS_PORT_5432_TCP_PORT
PG_PROMETHEUS_PORT_5432_TCP_PROTO
PG_PROMETHEUS_ENV_PG_PROMETHEUS_VERSION
PG_PROMETHEUS_PORT
PG_PROMETHEUS_ENV_TIMESCALEDB_VERSION
PG_PROMETHEUS_ENV_PG_SHA256
PG_PROMETHEUS_ENV_PG_MAJOR
PG_PROMETHEUS_NAME
PG_PROMETHEUS_PORT_5432_TCP
```

- getting identical error as @alexisph 
```
# /usr/local/bin/prometheus-postgresql-adapter 
/usr/local/bin/prometheus-postgresql-adapter flag redefined: log.level
panic: /usr/local/bin/prometheus-postgresql-adapter flag redefined: log.level

goroutine 1 [running]:
panic(0x8abe20, 0xc42014cf00)
	/usr/lib/golang/src/runtime/panic.go:500 +0x1a1
flag.(*FlagSet).Var(0xc42005a060, 0xbd6ee0, 0xc42014cea0, 0x964c51, 0x9, 0x97f73e, 0x63)
	/usr/lib/golang/src/flag/flag.go:791 +0x43e
prometheus-postgresql-adapter/vendor/github.com/prometheus/prometheus/vendor/github.com/prometheus/common/log.AddFlags(0xc42005a060)
	/opt/go/src/prometheus-postgresql-adapter/vendor/github.com/prometheus/prometheus/vendor/github.com/prometheus/common/log/log.go:122 +0xd4
prometheus-postgresql-adapter/vendor/github.com/prometheus/prometheus/vendor/github.com/prometheus/common/log.init.1()
	/opt/go/src/prometheus-postgresql-adapter/vendor/github.com/prometheus/prometheus/vendor/github.com/prometheus/common/log/log.go:110 +0x2d
prometheus-postgresql-adapter/vendor/github.com/prometheus/prometheus/vendor/github.com/prometheus/common/log.init()
	/opt/go/src/prometheus-postgresql-adapter/vendor/github.com/prometheus/prometheus/vendor/github.com/prometheus/common/log/syslog_formatter.go:127 +0xc5
prometheus-postgresql-adapter/vendor/github.com/prometheus/prometheus/storage/local.init()
	/opt/go/src/prometheus-postgresql-adapter/vendor/github.com/prometheus/prometheus/storage/local/test_helpers.go:73 +0x62
prometheus-postgresql-adapter/vendor/github.com/prometheus/prometheus/storage/remote.init()
	/opt/go/src/prometheus-postgresql-adapter/vendor/github.com/prometheus/prometheus/storage/remote/write.go:90 +0xb2
prometheus-postgresql-adapter/vendor/github.com/timescale/prometheus-postgresql-adapter/postgresql.init()
	/opt/go/src/prometheus-postgresql-adapter/vendor/github.com/timescale/prometheus-postgresql-adapter/postgresql/client.go:500 +0x65
main.init()
	/opt/go/src/prometheus-postgresql-adapter/main.go:267 +0x99
```

**Comment by erimatnor** [comment]
A new version of the adapter will be released soon (coming days) and it should take care of most of these issues.

**Comment by erimatnor** [comment]
@alexisph Just released v0.2. Note the new build instructions and switch to Dep for dependency management. Let me know if you continue to experience build issues.

**Comment by alexisph** [comment]
Thanks @erimatnor . It builds correctly now.

**Comment by alexisph** [comment]
Thanks @erimatnor . It builds correctly now.
